spring:
  application:
    name: server_registry

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10

  client:
    fetch-registry: false
    register-with-eureka: false
    registryFetchIntervalSeconds: 5

  server:
    eviction-interval-timer-in-ms: 30000
